### ISSUE TITLE
Offline clusters mess up with running cluster

### ISSUE THREAD

**Issue by runningman84** [kubetail-org/kubetail#245]
I have multiple context in my kubeconfig. The first context is a running cluster the other two contexts are test clusters which are offline most of the time. If I start kubetail I can see the pods of the first cluster, if I click on the logs of any pod I see a lot of errors in the log and I do not see anything because it seems that kubetail is trying to access the offline clusters:

```
➜  ~ kubetail serve
2025-05-03T17:08:02.729904665+02:00 INF Loaded default kubeconfig: /home/phil/.kube/config
2025-05-03T17:08:02.731471525+02:00 INF Started kubetail dashboard on http://localhost:7500/
W0503 17:08:05.779496    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:05.779546    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
W0503 17:08:09.166117    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:09.166161    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
W0503 17:08:15.166126    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:15.166189    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
W0503 17:08:19.062791    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:19.062832    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
W0503 17:08:28.072815    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:28.072854    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
W0503 17:08:45.992806    6619 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.EndpointSlice: Get "https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0": dial tcp 10.0.30.61:6443: connect: no route to host
E0503 17:08:45.992847    6619 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get \"https://10.0.30.61:6443/apis/discovery.k8s.io/v1/namespaces/kubetail-system/endpointslices?labelSelector=kubernetes.io%2Fservice-name%3Dkubetail-cluster-api&limit=500&resourceVersion=0\": dial tcp 10.0.30.61:6443: connect: no route to host" logger="UnhandledError"
```

**Comment by amorey** [comment]
Thanks for the bug report! We're working on this at the moment so it should be fixed shortly (see https://github.com/kubetail-org/kubetail/issues/190). Does the dashboard work as expected when you set the context to the working cluster?

**Comment by runningman84** [comment]
The dashboard itself works but I cannot access any logs.

**Comment by amorey** [comment]
Thanks again for the bug report. We were already working on the CLI error messages but I didn't realize that there was a deeper underlying problem. The issue was that health checks to multiple clusters were sharing the same mutex lock so often a problematic cluster would hold up the health checks for healthy clusters. The dashboard wasn't showing the logs because it was waiting for the health check to come back positive. The bug is fixed in the latest version (cli/v0.4.5). Homebrew usually takes ~1-2 hours to update or you can download it from the latest binaries [here](https://github.com/kubetail-org/kubetail/releases/latest).

**Comment by runningman84** [comment]
I see the git tag but I do not see the latest release.

**Comment by amorey** [comment]
Sorry, I forgot to publish the release. It's live now.

**Comment by runningman84** [comment]
It still does not work as expected, the size and last event column is "--" and I cannot see any log (it is loading forever). But the errors in the console aren't there anymore.

I also installed the Kubetail Cluster API but it did not help.

Btw. this is a talos cluster... it used to work with eks yesterday.

**Comment by amorey** [comment]
Ok, sorry that didn't fix the problem. It's normal to see "--" in the last event column if the dashboard can't reach the Kubetail Cluster API so it sounds like that's the source of the problem. I'll dig deeper into this and look into whether or not it could be related to the talos cluster. In the mean time, try uninstalling the Kubetail Cluster API (`kubetail cluster uninstall`) and make sure you're using v0.4.5 (`kubetail --version`).

**Comment by amorey** [comment]
I was able to reproduce the problem with Talos. Kubetail works fine for me when the Cluster API isn't installed but after I install it I'm seeing the same behavior as you. I'll dig into this further. I should have a bugfix out by tomorrow. In the mean time, try using it without the Cluster API. You should still be able to see logs, you just won't see last event timestamps and search won't be available.

**Comment by runningman84** [comment]
The daemon set does not work in talos because the kubetail ns does not have these labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

Adding them allowed the ds to run...

**Comment by runningman84** [comment]
Btw. for some reason it is detecting new logs but I cannot see any of the logs it just says Beginning of feed

**Comment by amorey** [comment]
Thanks! That’s very helpful

**Comment by amorey** [comment]
When I added the annotations you suggested to the namespace, everything worked fine including real-time tailing. Were you able to figure out why you can't see logs? Is your talos cluster remote or local?

Do you have any recommendations on how to handle security privileges in talos? Would you expect Kubetail's manifest to grant its own namespace those privileges or is that expected to be left to the user?

**Comment by amorey** [comment]
Quick update - to help with the permissions issues I'm going to try using a CSI-driver to give the cluster agent access to the node log directories instead of mounting the host paths directly. This fits better with k8s security patterns which will hopefully make deploying on talos smoother. My goal is to push out another release soon but it will probably take 1-2 days. In the mean time, let me know if Kubetail is working as expected without the cluster api installed and if you were able to figure out the issue with the cluster api installed.

**Comment by runningman84** [comment]
Even with the agent running it does not show any log:
![Image](https://github.com/user-attachments/assets/dd8e9e31-cc72-4791-b3cd-22dff8c17963)
I would advice to just use the k8s api to access the logs similar to the grafana alloy integration where the agent does not need any file access. This also allows it to record kuberentes event logs.
